# LAB 1

## Prepare environment

In [1]:
#!python -m pip install --upgrade pip
!python --version

Python 3.8.8


In [2]:
#!pip install numpy
#!pip install pandas
#!pip install scipy
#!pip install keras
#!pip install setuptools
#!pip install tensorflow
#!pip install tensorflow-datasets
#!pip install tensorflow-hub
#!pip install torch torchvision torchaudio

In [3]:
import numpy as np
import pandas as pd
import scipy
import keras
import setuptools
import tensorflow as tf
import torch

print('Numpy: ' + np.__version__)
print('Pandas: ' + pd.__version__)
print('Scipy: ' + scipy.__version__)
print('Keras: ' + keras.__version__)
print('Setuptools: ' + setuptools.__version__)
print('Tensorflow: ' + tf.__version__)
print('Torch: ' + torch.__version__)

Numpy: 1.20.2
Pandas: 1.2.3
Scipy: 1.4.1
Keras: 2.7.0
Setuptools: 59.2.0
Tensorflow: 2.7.0
Torch: 1.10.0+cpu


# What is Tensor ?

A tensor is a container which can house data in N dimensions, along with its linear operations, though there is nuance
in what tensors technically are and what we refer to as tensors in practice.

Mathematically speaking, tensors are more than simply a data container, however. Aside from holding numeric
data, tensors also include descriptions of the valid linear transformations between tensors. Examples of such
transformations, or relations, include the cross product and the dot product. From a computer science perspective,
it can be helpful to think of tensors as being objects in an object-oriented sense, as opposed to simply being a
data structure.

In [4]:
from IPython.display import Image
Image(url= "https://hadrienj.github.io/assets/images/2.1/scalar-vector-matrix-tensor.png")

Each tensor has some attributes:
- shape: number of elements on each axis
- rank: number of axes: scalar = 0, vector = 1, matrix = 2
- size: number of all elements of tensor

In [5]:
rank_0 = tf.constant(1)
rank_0

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [6]:
rank_1 = tf.constant([1.0, 2.0])
rank_1

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [7]:
rank_2 = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
rank_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)>

In [8]:
rank_3 = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])
rank_3

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])>

#### There are many ways you might visualize a tensor with more than two axes.

In [16]:
from IPython.display import Image
from IPython.display import display

x = Image(url= "https://www.tensorflow.org/guide/images/tensor/3-axis_numpy.png")
y = Image(url= "https://www.tensorflow.org/guide/images/tensor/3-axis_front.png")
z = Image(url= "https://www.tensorflow.org/guide/images/tensor/3-axis_block.png")
display(x, y, z)

You can convert a tensor to a NumPy array either using np.array or the tensor.numpy method:

In [10]:
np.array(rank_2)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)

In [11]:
rank_2.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)

Tensors often contain floats and ints, but have many other types, including:
- complex numbers
- strings

#### You can do basic math on tensors, including addition, element-wise multiplication, and matrix multiplication.

In [12]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]])

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [13]:
print(a + b, "\n") # element-wise addition
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [14]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# Find the largest value
print(tf.reduce_max(c))
# Find the index of the largest value
print(tf.argmax(c))
# Compute the softmax
print(tf.nn.softmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105854e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


Tensors have shapes. Some vocabulary:

- Shape: The length (number of elements) of each of the axes of a tensor.
- Rank: Number of tensor axes. A scalar has rank 0, a vector has rank 1, a matrix is rank 2.
- Axis or Dimension: A particular dimension of a tensor.
- Size: The total number of items in the tensor, the product shape vector.

In [40]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])
print("Type of every element:", rank_4_tensor.dtype)
print("Number of axes:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'float32'>
Number of axes: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


### Manipulating Shapes

In [22]:
# Shape returns a `TensorShape` object that shows the size along each axis
x = tf.constant([[1], [2], [3]])
print(x.shape)

(3, 1)


In [23]:
# You can convert this object into a Python list, too
print(x.shape.as_list())

[3, 1]


You can reshape a tensor into a new shape. The tf.reshape operation is fast and cheap as the underlying data does
not need to be duplicated.

In [24]:
# You can reshape a tensor to a new shape.
# Note that you're passing in a list
reshaped = tf.reshape(x, [1, 3])
print(x.shape)
print(reshaped.shape)

(3, 1)
(1, 3)


Typically the only reasonable use of tf.reshape is to combine or split adjacent axes (or add/remove 1s).

For this 3x2x5 tensor, reshaping to (3x2)x5 or 3x(2x5) are both reasonable things to do, as the slices do not mix:

In [25]:
print(tf.reshape(rank_3, [3*2, 5]), "\n")
print(tf.reshape(rank_3, [3, -1]))

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)


Reshaping will "work" for any new shape with the same total number of elements, but it will not do anything useful if you do not respect the order of the axes.

Swapping axes in tf.reshape does not work; you need tf.transpose for that.

In [26]:
# Bad examples: don't do this

# You can't reorder axes with reshape.
print(tf.reshape(rank_3, [2, 3, 5]), "\n")

# This is a mess
print(tf.reshape(rank_3, [5, 6]), "\n")

# This doesn't work at all
try:
  tf.reshape(rank_3, [7, -1])
except Exception as e:
  print(f"{type(e).__name__}: {e}")

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]], shape=(2, 3, 5), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]], shape=(5, 6), dtype=int32) 

InvalidArgumentError: Input to reshape is a tensor with 30 values, but the requested shape requires a multiple of 7 [Op:Reshape]
